name: Build and Push Backend Docker Image

on:
    push:
        branches:
            - main


jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Extract version
              id: extract_version
              run: |
                VERSION=$(git describe --tags --always)
                echo "VERSION=$VERSION" >> $GITHUB_ENV
                echo "::set-output name=VERSION::$VERSION"
  
            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/aure_backend:${{ steps.extract_version.outputs.VERSION }}
              